#!/bin/bash
path_file="$HOME/.config/lxqt/lxqt-powermanagement.conf"
if grep -q 'enableIdlenessWatcher=false' "$path_file"
	then
	sed -i 's/enableIdlenessWatcher=false/enableIdlenessWatcher=true/' "$path_file"
	notify-send -t 1500 -a Powermanagment -i user-idle "Idleness watcher enabled"

else
	sed -i 's/enableIdlenessWatcher=true/enableIdlenessWatcher=false/' "$path_file"
	notify-send -t 1500 -a Powermanagement -i user-idle "Idleness watcher disabled"
fi
